#!/usr/bin/env perl

use Config::IniFiles;
use strict;

# Read config
my $section='shock';
my $cfg = Config::IniFiles->new( -file => "/kb/deployment/deployment.cfg" );
my $scfg;
for my $p ( $cfg->Parameters($section)){
  $scfg->{$p}=$cfg->val($section,$p);
}

# Fix up config
my $file="/kb/deployment/services/shock_service/conf/shock.cfg";


my $mcfg=new Config::IniFiles( -file => $file) or die "Unable to open $file".$Config::IniFiles::errors[0];
$mcfg->newval('Address','api-port',$scfg->{'service-port'});
$mcfg->setval('Admin','email',$scfg->{'admin-email'}) if defined $scfg->{'admin-email'};
$mcfg->newval('Admin','users',$scfg->{'admin-users'}) if defined $scfg->{'admin-users'};

$mcfg->setval('Mongodb','hosts',$scfg->{'mongodb-host'});
$mcfg->newval('Mongodb','database',$scfg->{'mongodb-database'});
$mcfg->newval('Mongodb','user',$scfg->{'mongodb-user'});
$mcfg->newval('Mongodb','password',$scfg->{'mongodb-pwd'});

$mcfg->setval('Paths','site',$scfg->{'site'});
$mcfg->setval('Paths','data',$scfg->{'data'});
$mcfg->setval('Paths','logs',$scfg->{'logs'});

$mcfg->setval('Runtime','GOMAXPROCS',$scfg->{services}->{shock}->{'gomaxprocs'});

# added kkeller 20dec2016 for auth2 testing
$mcfg->setval('Auth','globus_token_url',$scfg->{'globus_token_url'}) if defined $scfg->{'globus_token_url'};
$mcfg->setval('Auth','globus_profile_url',$scfg->{'globus_profile_url'}) if defined $scfg->{'globus_profile_url'};
$mcfg->setval('External','api-url',$scfg->{'api-url'}) if defined $scfg->{'api-url'};
#globus_token_url=https://nexus.api.globusonline.org/goauth/token?grant_type=client_credentials
#globus_profile_url=https://nexus.api.globusonline.org/users
#api-url=https://ci.kbase.us/auth2/shock-api


$mcfg->WriteConfig($file);

