#!/usr/bin/env perl

use Config::IniFiles;
use strict;

# Read config
my $section='awe';
my $cfg = Config::IniFiles->new( -file => "/kb/deployment/deployment.cfg" );
my $acfg;
for my $p ( $cfg->Parameters($section)){
  $acfg->{$p}=$cfg->val($section,$p);
}

symlink "/mnt/awe/site","/var/www/awe_service" unless -e "/var/www/awe_service";

my $file="/kb/deployment/services/awe_service/conf/awe.cfg";
fix_config($file,$acfg);

fix_configjs("/mnt/awe/site/js/config.js");

sub fix_config {
  my $file=shift;
  my $acfg=shift;
# Fix up config

  my $mcfg=new Config::IniFiles( -file => $file) or die "Unable to open $file".$Config::IniFiles::errors[0];

# Update Mongo Params
  $mcfg->setval('Mongodb','hosts',$acfg->{'mongodb-host'});
  $mcfg->newval('Mongodb','database',$acfg->{'mongodb-database'});
  $mcfg->setval('Mongodb','user',$acfg->{'mongodb-user'});
  $mcfg->setval('Mongodb','password',$acfg->{'mongodb-pwd'});

#Update Ports
  $mcfg->setval('Ports','site-port',$acfg->{'site-port'});
  $mcfg->setval('Ports','api-port',$acfg->{'service-port'});
  $mcfg->setval('Admin','email','scanon@lbl.gov');
# Reuse mongo password
  $mcfg->setval('Admin','secretkey',$acfg->{'mongodb-pwd'});
  $mcfg->setval('Admin','users',$acfg->{'admin-user'});

# Update urls
  $mcfg->setval('External','site-url',$acfg->{'site-url'});
  $mcfg->setval('External','api-url',$acfg->{'api-url'});
# Update auth endpoints
  $mcfg->setval('Auth','globus_token_url',$acfg->{'globus_token_url'}) if defined $acfg->{'globus_token_url'};
  $mcfg->setval('Auth','globus_profile_url',$acfg->{'globus_profile_url'}) if defined $acfg->{'globus_profile_url'};

#globus_token_url=https://nexus.api.globusonline.org/goauth/token?grant_type=client_credentials
#globus_profile_url=https://nexus.api.globusonline.org/users



# Adjust some settings
  for my $param ('read','write','create-user'){
    $mcfg->setval('Anonymous',$param,'false');
  }
  for my $param ('delete','cg_read','cg_write','cg_delete'){
    $mcfg->newval('Anonymous',$param,'false');
  }
  $mcfg->WriteConfig($file);

}

sub fix_configjs {
  my $js=shift;
# Fix up config.js in the site area
#
  system("/bin/cp $js $js.orig");
  open(JSO, "$js.orig") or die "Unable to open $js.orig";
  open(JSN, "> $js");
  while(<JSO>){
    my $apiurl=$acfg->{'api-url'};
    #s/:7080/$apiurl/;
    s/ ":/ "$apiurl/;
    print JSN;
  }
}
